### ISSUE TITLE
Discuss about react config

### ISSUE THREAD

**Issue by thomasthiebaud** [trustpilot/node-eslint-config#21]
It seems that there is no common rules for react since there is no "real" react project yet. Here is an example of configuration

https://github.com/trustpilot/B2bIntegrationsApp/blob/master/.eslintrc

Is possible to agree on react rules so all react project has the same ? If we do it well, this config file can be reduce to only

```
{
  "extends": [
    "trustpilot/react"
  ]
}
```

**Comment by b-dur** [comment]
My only concern is, that we don't create a react config that is tailored our b2b apps. Think the goal must be that any react project in Trustpilot could use this config.

**Comment by martinbuberl** [comment]
I agree with @b-dur . Let's use a config with sane defaults that are used by the JS-community (e.g. https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

**Comment by madsgodvinjensen** [comment]
I think the React config we have now is a bit old and doesn't really support modern style JS and React. Airbnb's config is a pretty decent starting point, but I think there are a few rules in there I would like to disable or change a bit. I'm happy to start from theirs though and then discuss.

**Comment by madsgodvinjensen** [comment]
I started a PR with some commits that reflect my opinions on React style. I may have missed some things and don't necessarily feel too strong about all the changes, but let's discuss!

https://github.com/trustpilot/node-eslint-config/pull/23

**Comment by DanMeakin** [comment]
I looked through the pull request, and it all looks reasonable to me. I think we probably just need to work with the new config and see if we come up against any problems.

**Comment by martinbuberl** [comment]
@DanMeakin Moving forward, use GH's review feature and leave that comment as part of your review ;)

**Comment by martinbuberl** [comment]
Closing as https://github.com/trustpilot/node-eslint-config/pull/23 got merged.
