### ISSUE TITLE
The no-var rule is set to 0 in our ES6 config

### ISSUE THREAD

**Issue by bapjiws** [trustpilot/node-eslint-config#25]
Is there any rationale behind setting the ```no-var``` rule to 0 in [our ES6 config](https://github.com/trustpilot/node-eslint-config/blob/master/rules/eslint/es6.js#L32)? I was about to submit a PR, but perhaps there are reasons to this decision that still hold.

**Comment by b-dur** [comment]
I think we should change it to `error`. This will however result in many breaking projects, but I think it would be worth it.

**Comment by martinbuberl** [comment]
The motivation was to slowly introduce eslint and integrate it in our projects without breaking everything. [See also](https://eslint.org/docs/rules/no-var#when-not-to-use-it):

> **When Not To Use It**
> In addition to non-ES6 environments, existing JavaScript projects that are beginning to introduce ES6 into their codebase may not want to apply this rule if the cost of migrating from var to let is too costly.

Anyhow, I think we're in a much better state now and I agree with @b-dur that we can change it to error and bump the major indicating a breaking change.

**Comment by bapjiws** [comment]
@b-dur @martinbuberl Thanks for the feedback, guys, the PR is ready.
