### ISSUE TITLE
Use Prettier for code formatting

### ISSUE THREAD

**Issue by DanMeakin** [trustpilot/node-eslint-config#40]
Prettier is a tool focused solely on formatting code to keep a consistent style. For those who don't know the tool:

> Prettier is an opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary.

It typically uses a pretty minimal set of rules and is intended to be run on save or as a pre-commit hook. It doesn't warn the user about formatting issues, it just fixes them.

I suggest that we drop all code formatting rules from our ESLint config, and focus only on substance issues. That way, the linter will only flag issues concerning logic, expression, etc. to the developer and remove a lot of the noise you currently receive relating to style issues.

**Comment by martinbuberl** [comment]
I disagree. We should have one tool with all rules, be it purely formatting or not and ESLint can do that for us. It's hard enough to maintain this library and it acts as our de-facto style guide "if you can't lint it, it can't be a rule."

I don't see any issues for developers additionally setting up and using Prettier. Should work well together and complement ESLint nicely.

**Comment by madsgodvinjensen** [comment]
Does prettier work with Typescript?

**Comment by martinbuberl** [comment]
@madsgodvinjensen yes, it does:
https://github.com/prettier/prettier/issues/13#issuecomment-305832943

**Comment by deesouky** [comment]
I'm currently using Prettier with the linter, and it essentially amounts to the what @DanMeakin is suggesting anyway, it handles all of the formatting rules. So the only issues that get flagged by the linter for me at the moment are code-quality issues. 
It makes the formatting rules in the linter redundant, true, but maybe it would be an idea for us to start by standardising the use of prettier in our stack, and then re-examine the necessity of maintaining the linter formatting rules at a later point.

**Comment by pmrcunha** [comment]
I think Prettier is a more powerful formatter than eslint, and that it would be positive to use it, if not instead of our eslint style rules, at least beside them (using prettier-eslint). What I think would defeat the point would be to configure Prettier — we should just use the standard config.

On the risk of being polemic, I'll even suggest we use StandardJS and make this eslint rules discussion our last 😄
I like my semi-colons, but that's a compromise I would be willing to make.
https://standardjs.com/

**Comment by DanMeakin** [comment]
Thanks for all the comments. My own perspective on this (which I didn't want to expand upon too much initially) is that we should be using automated tools where possible which make life easier for us. Prettier can single-handedly and automatically deal with styling in JS. As developers we have one less thing to worry about.

Prettier's approach to fixing style is, in my opinion, better than that of ESLint: it takes an AST representation of the code to be styled, and then reprints the code in accordance with the its rules. It is, I think, quite like `gofmt`. You don't get errors or warnings about stylistic problems; they are simply fixed for you on save/commit.

It does take a fairly opinionated approach to code style, but does allow for some configuration. The result of this is that your configuration concerning styling is very small, versus the sizeable configuration of ESLint for this.

There is a problem at present with using Prettier together with ESLint: you are never going to bring the rules of both tools 100% into alignment, so you will still see linter errors for style issues. This negates the benefits of a tool which simply fixes problems without notifying the developer. So, you still need to deal with messages concerning style problems.

I think it is nice to have one tool which handles linting-related matters. However, when we can use two tools which do have somewhat different concerns, such as Prettier and ESLint, I think we should not reject that simply because of a desire only to use one tool.

**Comment by DanMeakin** [comment]
The Frontend Group discussed this at our meeting on Wednesday. We agreed that it would make most sense to adopt Prettier as a part of our common JS tooling. As I understand it, there were two main reasons for this:

1.  Using Prettier alongside ESLint will give us a better consistency across codebases, removing more of the visual noise you often find when switching contexts. Because of the way Prettier works, it will simply do a better job of automatically handing this. It was compared favourably to `gofmt` in this regard.

2. Prettier has a very restricted set of options, and supersedes a large number of ESLint rules. As such, we can drop a substantial number of linting rules which are no longer relevant, and maintain a more slim repository of rules.

I undertook to make a PR implementing what we decided; this is #43. As well as removing many formatting rules, this PR adds a Prettier plugin to ESLint and defines set of Prettier rules which reflect as far as possible what we previously had in our ESLint rules. Prettier will run as part of `eslint --fix` under this configuration.

Does this do what we hope/intend? What are everyone's views on this?

**Comment by madsgodvinjensen** [comment]
This is great. I'm happy with the prettier plugin - didn't know that existed. That definitely makes things easier.

I left one comment on the PR though.

**Comment by pmrcunha** [comment]
Awesome job! It will be nice not having to go back and break lines that are too long and other formatting tasks. And getting less noisy git diffs.

**Comment by noxxious** [comment]
the same goes with prettier+ typescript integration via ts-lint plugin. I'm using the setup in most of my projects:
- eslint + eslint prettier plugin (tweaking only line length to 120 or 140)
- tslint + tslint-plugin-prettier + tslint-config-prettier
- husky + lint-staged  (pre-commit and pre-push git hooks) to enforce formatting on commits

This worked very well with my previous large team. The only thing we voted for was the line length.

**Comment by DanMeakin** [comment]
#43 has now been merged, resolving this. This is now [v4.0.0](https://github.com/trustpilot/node-eslint-config/releases/tag/v4.0.0). Let's see how Prettier integration goes!
